# -*- coding: utf-8 -*-
"""Anomaly Detection Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118VMwx1ck8RiBi7fyRqZmcHTL4m2kV2k
"""

import pandas as pd

df = pd.read_csv("Raw Transactions.csv")
print("CSV loaded successfully!")
df

# Create a feature column
df["amount_feature"] = df["amount"]

# Show the updated data
df

from pyod.models.iforest import IForest

# Create and train the model
model = IForest(contamination=0.05)
model.fit(df[["amount_feature"]])

# Predict anomalies
df["anomaly"] = model.predict(df[["amount_feature"]])
df["score"] = model.decision_function(df[["amount_feature"]])

df

# Generate alerts
alerts = df[df["anomaly"] == 1]

alerts

def severity(score):
    if score > 0:
        return "HIGH"
    else:
        return "MEDIUM"

alerts["severity"] = alerts["score"].apply(severity)
alerts